### ISSUE TITLE
Issue with pivot model and deferred binding

### ISSUE THREAD

**Issue by josheigel** [daftspunk/oc-crm-plugin#2]
Thank you so much for your tutorial by the way! I followed it and love the detail since I'm a bit of a newbie when it comes to Laravel and October CMS.

However, I am having one problem when I attempt to enter a new offering in an opportunity that has not yet been saved. I can move through selecting an opportunity as well as the pop-up with the price, cost and owner, but when I attempt to add that pivot relationship to my 'opportunities_offerings' table, I get the following SQL error.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'opportunity_id' cannot be null (SQL: insert into 'crm_opportunities_offerings' ('offering_id', 'opportunity_id') values (4,))' on line 624 of ../Database/Connection.php'
```

I've messed around with the relationships, but then it dawned on me that it could potentially be a deferred binding issue since the opportunity_id really isn't created yet. I saw the option to set 'deferredBinding' to true in my config_relation.yaml file, however that didn't work.

I'm sure I'm messing something up, but I have looked over your code and tried to simply duplicate every line just to ensure I'm understanding the relationships, models, etc.

Any help is appreciated. Thanks!

**Comment by scosist** [comment]
Ditto, great tutorial but I'm running into this issue as well. Been through this a number of times and it doesn't look like deferredBinding is being used. Could somebody please elaborate on how this is supposed to work?

**Comment by Floriskoch** [comment]
Same issue here, please provide some instructions on how to fix this. Thanks!

**Comment by daftspunk** [comment]
This will be covered by https://github.com/octobercms/october/issues/1409

The support demand for October is increasing, while the available time the maintainers have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- Make a [financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
