### ISSUE TITLE
Json displaying rather than firstname

### ISSUE THREAD

**Issue by voodookid00** [daftspunk/oc-crm-plugin#3]
In the assigned to column in offering it shows the full json rather than just the first name. In the opportunityofferingpivot it is using pivot[owner][first_name]

**Comment by BlazL** [comment]
I have the same problem.

**Comment by daftspunk** [comment]
ACK

**Comment by BlazL** [comment]
Is there already any solution? Or maybe, how can solve this problem with partial?

**Comment by daftspunk** [comment]
This will be fixed in October Build 380+
